// Generated by CoffeeScript 1.8.0
(function() {
  var nock;

  nock = require('nock');

  exports.init = (function(_this) {
    return function(app, config) {
      app.get('/lodash/lodash.js', function(req, res) {
        return res.sendfile(__dirname + '/node_modules/lodash/lodash.js');
      });
      app.get('/backbone/backbone.js', function(req, res) {
        return res.sendfile(__dirname + '/node_modules/backbone/backbone.js');
      });
      app.get('/jquery.js', function(req, res) {
        return res.sendfile(__dirname + '/bower_components/jquery/dist/jquery.js');
      });
      app.get('/pixi.js', function(req, res) {
        return res.sendfile(__dirname + '/bower_components/pixi.js/bin/pixi.dev.js');
      });
      app.get('/bco/client.js', function(req, res) {
        return res.sendfile(__dirname + '/bco/client.js');
      });
      app.get('/bco/client.js.map', function(req, res) {
        return res.sendfile(__dirname + '/bco/client.js.map');
      });
      return app.get('/-bco', function(req, res) {
        return res.sendfile(__dirname + '/public/dev.html');
      });
    };
  })(this);

}).call(this);

//# sourceMappingURL=app_dev.js.map
