// Generated by CoffeeScript 1.8.0
(function() {
  var exec;

  exec = require('child_process').exec;

  module.exports = function(grunt) {
    var exec_callback;
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.initConfig({
      watch: {
        coffee: {
          files: ['../**/*.coffee']
        },
        sass: {
          files: 'public/d/sass/screen.sass'
        },
        "static": {
          files: ['public/d/**/*.css', 'public/**/*.html', 'public/**/*.js', 'public_test/**/*.js'],
          options: {
            livereload: true
          }
        }
      }
    });
    exec_callback = function(error, stdout, stderr) {
      if (error) {
        return console.log('exec error: ' + error);
      }
    };
    grunt.event.on('watch', function(event, file, ext) {
      if (ext === 'coffee') {
        exec("coffee -m -c " + file, exec_callback);
      }
      if (ext === 'sass') {
        return exec("cd public/d && compass compile --sourcemap sass/screen.sass", exec_callback);
      }
    });
    return grunt.registerTask('default', ['watch']);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
