// Generated by CoffeeScript 1.3.3
(function() {
  var Router, events,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  events = require('events');

  module.exports = Router = (function(_super) {

    __extends(Router, _super);

    function Router(options, db) {
      this.db = db;
      this.send = new events.EventEmitter();
    }

    Router.prototype.connection = function(socket) {
      var _this = this;
      socket.on('login:request', function(data) {});
      return socket.on('disconnect', function() {});
    };

    return Router;

  })(events.EventEmitter);

}).call(this);
