// Generated by CoffeeScript 1.6.3
(function() {
  describe('Rooms', function() {
    var r;
    r = null;
    beforeEach(function() {
      r = new App.Rooms({
        'monitor': 1
      });
      return r.$el.appendTo(document.body);
    });
    afterEach(function() {
      return r.remove();
    });
    return describe('render rooms', function() {
      it('add/remove room', function() {
        r.render();
        expect(r.$('>li')).to.have.length(0);
        r.room_add({
          'id': 1,
          'users': [
            {
              'id': 10,
              'name': ''
            }
          ]
        });
        r.room_add({
          'id': 2,
          'users': []
        });
        expect(r.$('>li').length).to.be(2);
        expect(r.$('>li:eq(0)').attr('data-pk')).to.be('2');
        expect(r.$('>li:eq(1)').attr('data-pk')).to.be('1');
        expect(r.$('>li:eq(0)>ul>li').length).to.be(0);
        expect(r.$('>li:eq(1)>ul>li').length).to.be(1);
        r.room_remove({
          'id': 1
        });
        expect(r.$('>li').length).to.be(1);
        return expect(r.rooms[1]).to.be(void 0);
      });
      it('add/remove user', function() {
        r.render();
        expect(r.$('>li')).to.have.length(0);
        r.room_add({
          'id': 1,
          'users': []
        });
        expect(r.$('>li:eq(0)>ul>li')).to.have.length(0);
        r.user_join({
          'room_id': 1,
          'user': {
            'id': 3,
            'name': 'Ze'
          }
        });
        expect(r.$('>li:eq(0)>ul>li')).to.have.length(1);
        r.user_join({
          'room_id': 1,
          'user': {
            'id': 4,
            'name': 'Zebra'
          }
        });
        expect(r.$('>li:eq(0)>ul>li')).to.have.length(2);
        expect(r.$('>li:eq(0)>ul>li:eq(0)').attr('data-pk')).to.be('3');
        expect(r.$('>li:eq(0)>ul>li:eq(0) strong').html()).to.be('Ze');
        r.user_left({
          'room_id': 1,
          'user_id': 4
        });
        return expect(r.$('>li:eq(0)>ul>li')).to.have.length(1);
      });
      it('change full', function() {
        r.render([
          {
            'id': 1,
            max: 2,
            'users': [
              {
                'id': 10
              }
            ]
          }
        ]);
        expect(r.$('>li')).to.have.length(1);
        expect(r.$('>li:eq(0) button').is(':disabled')).not.be.ok();
        r.user_join({
          'room_id': 1,
          'user': {
            'id': 11
          }
        });
        expect(r.$('>li:eq(0) button').is(':disabled')).to.be.ok();
        r.user_left({
          'room_id': 1,
          'user_id': 10
        });
        expect(r.$('>li:eq(0) button').is(':disabled')).not.be.ok();
        r.user_left({
          'room_id': 1,
          'user_id': 11
        });
        return expect(r.$('>li:eq(0) button').is(':disabled')).not.be.ok();
      });
      it('trigger join', function() {
        var spy;
        r.render([
          {
            'id': 1,
            'users': []
          }
        ]);
        r.room_add({
          'id': 2,
          'users': []
        });
        spy = sinon.spy();
        r.on('join', spy);
        r.$('>li[data-pk="1"] button').click();
        expect(spy.callCount).to.be(1);
        expect(spy.getCall(0).args[0]).to.be(1);
        r.$('>li[data-pk="2"] button').click();
        return expect(spy.getCall(1).args[0]).to.be(2);
      });
      it('monitor id on join', function() {
        var spy;
        spy = sinon.spy();
        r.on('monitor:add', spy);
        r.render([
          {
            'id': 1,
            'users': [
              {
                'id': 1,
                'name': ''
              }
            ]
          }
        ]);
        r.user_join({
          'room_id': 1,
          'user': {
            'id': 2,
            'name': ''
          }
        });
        return expect(spy.callCount).to.be(1);
      });
      it('monitor id on remove user', function() {
        var spy;
        r.render([]);
        spy = sinon.spy();
        r.on('monitor:remove', spy);
        r.render([
          {
            'id': 1,
            'users': [
              {
                'id': 1,
                'name': ''
              }, {
                'id': 2,
                'name': ''
              }
            ]
          }
        ]);
        r.user_left({
          'room_id': 1,
          'user_id': 2
        });
        r.user_left({
          'room_id': 1,
          'user_id': 1
        });
        return expect(spy.callCount).to.be(1);
      });
      it('monitor id on remove room', function() {
        var spy;
        spy = sinon.spy();
        r.on('monitor:remove', spy);
        r.render([
          {
            'id': 1,
            'users': [
              {
                'id': 1,
                'name': ''
              }
            ]
          }, {
            'id': 2,
            'is_full': false,
            'users': []
          }
        ]);
        r.room_remove({
          'id': 2
        });
        r.room_remove({
          'id': 1
        });
        return expect(spy.callCount).to.be(1);
      });
      return it('monitor id on remove room and user', function() {
        var spy;
        spy = sinon.spy();
        r.on('monitor:remove', spy);
        r.render([
          {
            'id': 1,
            'users': [
              {
                'id': 1,
                'name': ''
              }
            ]
          }
        ]);
        r.user_join({
          'room_id': 1,
          'user': {
            'id': 1
          }
        });
        r.room_remove({
          'id': 1
        });
        return expect(spy.callCount).to.be(1);
      });
    });
  });

  describe('Create Room', function() {
    return describe('new room', function() {
      var r, spy;
      r = null;
      spy = null;
      beforeEach(function() {
        r = new App.CreateRoom();
        r.$el.appendTo(document.body);
        r.render();
        spy = sinon.spy();
        return r.on('create', spy);
      });
      afterEach(function() {
        return r.remove();
      });
      return it('trigger event (default)', function() {
        r.$('button').click();
        return expect(spy.callCount).to.be(1);
      });
    });
  });

}).call(this);
